### ISSUE TITLE
Background Tiles

### ISSUE THREAD

**Issue by JenG1** [kshep425/JKReady#5]
For the demo, create the 'fixed' instance and the 'broken' instance for each background tile. Should have the ability to switch from 'broken' to 'fixed' depending on the user's answer.

**Comment by kshep425** [comment]
There also needs to be intermediate so if they choose the wrong option that shows what happens to the page too.

**Comment by kshep425** [comment]
Kind of like Goldilocks...too large, too small, just right

**Comment by kshep425** [comment]
maybe each option can have a question mark link to explain what it does...for example if we decide to have a float left option we could have the definition of float left in a modal or popup.

**Comment by JenG1** [comment]
Done.
